version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - "${BACKUP_STORAGE_PATH:-/app/backups}:/app/backups"
      - "${SSH_KEYS_PATH:-~/.ssh}:/root/.ssh:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health" || "exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app-backups:
    driver: local
