/* AUTO-GENERATED by scripts/sync-changelog.ts — do not edit by hand.
 * Source of truth: repo-root CHANGELOG.md
 * Regenerate: bun run sync-changelog (also runs on prebuild)
 */

export type ChangelogSection = {
  heading: string;
  items: readonly string[];
};

export type ChangelogEntry = {
  id: string;
  title: string;
  date: string;
  intro?: string;
  sections: readonly ChangelogSection[];
};

export const changelogEntries: readonly ChangelogEntry[] = [
  {
    "id": "unreleased",
    "title": "Unreleased",
    "date": "main",
    "sections": [
      {
        "heading": "Added",
        "items": [
          "Landing changelog sync — /changelog is generated from this file at landing build time (landing/scripts/sync-changelog.ts); no hand mirror.",
          "Landing compare page (/compare) — LazyBackup vs rsync/cron, with short notes on Restic, Borg, and Duplicati. Positions LazyBackup as a From→To control plane (SSH, Docker volumes, DB dumps, MCP), not a dedup archive CLI.",
          "Landing changelog (/changelog) — user-facing release notes on the static site.",
          "MCP demo callout on the marketing home page — links to the manage backups with MCP guide.",
          "Screenshot gallery entries for Status, Encryption (age vault), API/MCP settings, S3 profiles, and Bro Space (capture when a seeded UI is available)."
        ]
      },
      {
        "heading": "Reliability (recent main)",
        "items": [
          "CI — tests and build before GHCR publish; Alpine/musl regressions caught in the image pipeline.",
          "Concurrent-run lock — the same backup config cannot overlap itself.",
          "Failure webhooks — notify on failed runs; method, headers, and {{tag}} body templates (Settings).",
          "Backup validate — probes without transferring data; last validation results persist on the config.",
          "Secret redaction — server, S3, and backup API responses strip secrets before JSON leaves the process."
        ]
      },
      {
        "heading": "Product surface (context for evaluators)",
        "items": [
          "Also on recent main (see README / Features for detail): age encryption vault, Bro Space peer destinations, instance meta-backup, WebAuthn passkeys, Status posture page, S3-compatible endpoints, database dumps, MCP + API tokens with optional remote_exec."
        ]
      }
    ]
  }
] as const;
